language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update 1.10.1
  - composer install --no-interaction

script:
  - php artisan key:generate
  - vendor/bin/phpunit

services:
  - redis-server

cache:
  directories:
    - vendor 